identifier_name:
  min_length:
    warning: 0
    error: 0
nesting:
  type_level: 3
excluded:
  - Carthage
  - Pods
disabled_rules:
  - trailing_whitespace
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - file_header
  - force_cast
  - force_try
  - line_length
